### PR TITLE
Update tag type

### PR DESCRIPTION
**Pull request by EmmanuelDrouin**
- Remove type--partner and type--community
- Add type--orange, type--green, type--purple

### CODE REVIEW

**Comment by EmmanuelDrouin** [comment]
@antho1404 ready for review

**Review by antho1404 — CHANGES_REQUESTED** [review]
If we change the type by color, we should use a property color and not type then

**Comment by EmmanuelDrouin** [comment]
Ok i will do the changes

**Review by antho1404 — CHANGES_REQUESTED** [review]
I'm really not sure about this PR.
Adding the color instead of a type is great but adding a color that can just be one or the other is not good.

What's the reason for this change?

Either we keep as it is or we support the color properly with the possibility to pass an hexa code or something like that.

If we go with the color, the documentation needs to be updated.

**Comment by EmmanuelDrouin** [comment]
> I'm really not sure about this PR.
> Adding the color instead of a type is great but adding a color that can just be one or the other is not good.
> 
> What's the reason for this change?
> 
> Either we keep as it is or we support the color properly with the possibility to pass an hexa code or something like that.
> 
> If we go with the color, the documentation needs to be updated.

As we added new MESG secondary colors to the chart, the types "partners" and "community" are out of the subject. the colors won't be related to only one type, but will be related to a category of situations. I don't plan to use more colors then the fourth i added to this PR, otherwise they will be out of the MESG chart.

I'm ok to add the possibility to customize the color of the tag with an hexa code, if in the future we need for a special situation to go out of the brand colors.

We should switch to color instead of type to have something simpler to use for different situation. Will be weird to use a type partner for something that is not related to a partner just because we want to use the orange tag.

**Comment by EmmanuelDrouin** [comment]
@antho1404 changes done

**Review by antho1404 — APPROVED** [review]

**Pull request merged**
