### PR TITLE
Add tab component.

### PR DESCRIPTION
**Pull request by patjanawat**
[x] Create tab component (**Closes**https://github.com/mesg-foundation/mesg-components/issues/24)

### CODE REVIEW

**Review by antho1404 — COMMENTED** [review]
How do I use this component and know which button was clicked or put some content associated in the tab.
This is not a tab, at best it's a "group button" .
A tab is something like https://github.com/cristijora/vue-tabs or https://jsfiddle.net/b44cc4dq/187/

**Comment by patjanawat** [comment]
> How do I use this component and know which button was clicked or put some content associated in the tab.
> This is not a tab, at best it's a "group button" .
> A tab is something like https://github.com/cristijora/vue-tabs or https://jsfiddle.net/b44cc4dq/187/

Fixing

**Comment by patjanawat** [comment]
> > How do I use this component and know which button was clicked or put some content associated in the tab.
> > This is not a tab, at best it's a "group button" .
> > A tab is something like https://github.com/cristijora/vue-tabs or https://jsfiddle.net/b44cc4dq/187/
> 
> Fixing

Done.

**Review by antho1404 — APPROVED** [review]

**Comment by antho1404** [comment]
@patjanawat could you fix the conflicts and then it is ready to merge :)

**Comment by patjanawat** [comment]
> @patjanawat could you fix the conflicts and then it is ready to merge :)

Done.

**Pull request merged**
