### PR TITLE
Update icons button

### PR DESCRIPTION
**Pull request by EmmanuelDrouin**
- Update icons from solid to light

### CODE REVIEW

**Comment by EmmanuelDrouin** [comment]
We should wait, for the next PR (colors scss update) before merging this one, as it's gonna impact this one.

**Comment by EmmanuelDrouin** [comment]
@antho1404 ready for review

**Review by antho1404 — CHANGES_REQUESTED** [review]
Please revert the changes on the package-lock from charts

**Comment by EmmanuelDrouin** [comment]
Done ;)

**Review by antho1404 — APPROVED** [review]

**Pull request merged**
